[package]
name = "rs-woff"
version = "0.1.0"
edition = "2021"
exclude = [
    "target/",
    "test_assets/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.25"
